apps/estates/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    url(r'^create/$', 'estates.views.create', name='apartment-create'),
    url(r'^create_xml/$', 'estates.views.create_xml_objects', name='create-appartments-via-xml'),
    url(r'^list/$', 'estates.views.estates_list', name='apartment-list'),
    url(r'^edit/(\d+)/$', 'estates.views.edit', name='apartment-edit'),
    url(r'^view/(\d+)/$', 'estates.views.view', name='apartment-view'),
    url(r'^bookmark/(\d+)/$', 'estates.views.add_to_bookmarks', name='apartment-bookmark'),
    url(r'^bookmark_delete/(\d+)/$', 'estates.views.remove_from_bookmarks', name='apartment-bookmark-remove'),
    url(r'^bookmarks/$', 'estates.views.bookmarks', name='bookmarks'),
    url(r'^cart/$', 'estates.views.cart', name='cart'),
    url(r'^publish/$', 'estates.views.publish', name='publish'),
    url(r'^unpublish/$', 'estates.views.unpublish', name='unpublish'),
    url(r'^delete/$', 'estates.views.delete', name='delete-apartment'),
	# openimmo
    url(r'^openimmo/$', 'estates.openimmo.upload', name='openimmo-page'),
    url(r'^xmlse/$', 'estates.views.xmlse', name='xmlse-s'),
)

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.conf import  settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^$', 'estates.views.index'),
    url(r'^migrate/$', 'estates.views.migrate'),
    url(r'^search/$', 'estates.views.search', {'students':False}, name='search'),
    url(r'^search/students/$', 'estates.views.search', {'students':True}, name='search-students'),
    (r'^user/', include('users.urls')),
    (r'^tarifs/', include('tarifs.urls')),
    (r'^pricing/', 'pages.views.pricing'),
    (r'^estates/', include('estates.urls')),
    (r'^world/', include('world.urls')),
    (r'^admin/', include(admin.site.urls)),
    #Converter
    url(r'^ajax_converter/$', 'pages.views.convert',name='ajax-converter'),
    # Pages app
    url(r'^page/organisation/$', 'pages.views.organisation', name='page-organisation'),
    url(r'^page/(.+)/$', 'pages.views.show_page', name='view-page'),
    url(r'^news/$', 'pages.views.show_all_news', name='view-all-news'),
    url(r'^news/(\d+)/$', 'pages.views.show_news_page', name='view-news'),
    url(r'^country/(\d+)/$', 'pages.views.show_country_info', name='country-info'),
    url(r'^contacts/$', 'pages.views.contacts', name='view-contacts'),
    url(r'^services/(.+)/$', 'pages.views.iframe_page'),
    (r'^messages/', include('django_messages.urls')),
    (r'^grappelli/', include('grappelli.urls')),

    (r'^password/reset/$', 'django.contrib.auth.views.password_reset',
    {'post_reset_redirect' : '/password/reset/done/'}),
    (r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm',
    {'post_reset_redirect' : '/password/done/'}),
    (r'^password/done/$', 'django.contrib.auth.views.password_reset_complete'),

    (r'^companies/$', 'users.views.companiesList'),

    ##################################

    (r'^search/country/(?P<country>\d+)-(?P<slug>.+)/$', 'estates.views.searchByCountry'),
    url(r'^(?P<estate_type>.*)-in-region-(?P<region>\d+)/$', 'estates.views.filterByRegionEndType', name='filterByRegionEndType'),
    # Created in second box in search sidebar
    url(r'^(?P<estate_type>\w+)-in-(?P<country>\d+)-(.+)/$', 'estates.views.filterByCountryEndType', name='filterByCountryEndType'),
    url(r'^rent-(?P<estate_type>\w+)-in-(?P<country>\d+)-(.+)/$', 'estates.views.filterRentByCountryEndType', name='filterRentByCountryEndType'),
    url(r'^country-(?P<country_id>\d+)-(.+)/city-(?P<city_id>\d+)$', 'estates.views.filterByCity', name='filterByCity'),
    url(r'^country-(?P<country_id>\d+)-(.+)/region-(?P<region_id>\d+)$', 'estates.views.filterByRegion', name='filterByRegion'),
    url(r'^estate-type-(?P<estate_type>\w+)$', 'estates.views.filterByEstateType', name='filterByEstateType'),

    (r'^robots.txt$', 'estates.views.robots'),
    (r'^googled5314acba1fdabf8.html$', 'django.views.static.serve', {'path':"/googled5314acba1fdabf8.html",'document_root': settings.MEDIA_ROOT,'show_indexes': False }),
    (r'^cmsmagazine5dbde1f1d2f07da9d8519fcfe2f0e8b5.txt$', 'django.views.static.serve', {'path':"/cmsmagazine5dbde1f1d2f07da9d8519fcfe2f0e8b5.txt",'document_root': 
settings.MEDIA_ROOT,'show_indexes': False }),

)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

# rosetta
#from django.conf import settings
#if 'rosetta' in settings.INSTALLED_APPS:
#    urlpatterns += patterns('',
#        url(r'^rosetta/', include('rosetta.urls')),
#    )

apps/estates/models.py
# -*- coding: utf-8 -*-
import Image
import os

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import  ugettext_lazy as _
from django.conf import settings

from annoing.currencyManager import currencyManager
from estates.choices import *
from world.models import *
        
class  KitchenChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=KITCHEN_OPTIONS)
    use_list = KITCHEN_OPTIONS
    
    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(KITCHEN_OPTIONS[index][1])

    class Meta:
        verbose_name = _(u"Кухня")

class  ComfortChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=COMFORT_OPTIONS)
    use_list = COMFORT_OPTIONS
    
    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(COMFORT_OPTIONS[index][1])

    class Meta:
        verbose_name = _(u"Комфорт")

class  RentForChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=RENT_FOR_CHOICES)
    use_list = RENT_FOR_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(RENT_FOR_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Сдается арендатору")

class  LocationChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=LOCATION_CHOICES)
    use_list = LOCATION_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(LOCATION_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Расположение")

class  FloorTypeChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=FLOOR_TYPE_CHOICES)
    use_list = FLOOR_TYPE_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(FLOOR_TYPE_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Тип этажа")

class  HeatingOptions(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=HEATING_CHOICES)
    use_list = HEATING_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(HEATING_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Тип отопления")

class  FloorCoveringOptions(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=FLOOR_COVERING_CHOICES)
    use_list = FLOOR_COVERING_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(HEATING_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Покрытие пола")

class  BathroomChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=BATHROOM_CHOICES)
    use_list = BATHROOM_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(BATHROOM_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Ванная комната")

class  OtherFacilitieChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=OTHER_FACILITIES_CHOICES)
    use_list = OTHER_FACILITIES_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(OTHER_FACILITIES_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Другие помещения")

class  SecuritySystemsChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=SECURITY_SYSTEMS_CHOICES)
    use_list = SECURITY_SYSTEMS_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(SECURITY_SYSTEMS_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Системы безопасности")

class  FurnishingChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=FURNISHING_CHOICES)
    use_list = FURNISHING_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(FURNISHING_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Меблировка")

class  AdditionalEquipmentChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=ADDITIONAL_EQUIPMENT_CHOICES)
    use_list = ADDITIONAL_EQUIPMENT_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(ADDITIONAL_EQUIPMENT_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Дополнительное оснащение")


class  GlazingChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=GLAZING_CHOICES)
    use_list = GLAZING_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(GLAZING_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Остекление")


class  GlassFrameChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=GLASS_FRAME_CHOICES)
    use_list = GLASS_FRAME_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(GLASS_FRAME_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Стекольные рамы")

class  WindowViewChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=WINDOW_VIEW_CHOICES)
    use_list = WINDOW_VIEW_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(WINDOW_VIEW_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Вид из окна")


class  ConditionChoices(models.Model):
    options = models.CharField(max_length=15, blank = True, choices=CONDITION_CHOICES)
    use_list = CONDITION_CHOICES

    def __unicode__(self):
        index = int(self.options) - 1
        return unicode(CONDITION_CHOICES[index][1])

    class Meta:
        verbose_name = _(u"Состояние")


class Apartament(models.Model):
    '''
    Model for handling all objects and its relations
    '''
    def __init__(self,*args,**kwargs):
        super(Apartament, self).__init__(*args,**kwargs)

    user = models.ForeignKey(User)
    # Determinate is object paid and published
    is_published = models.BooleanField(_(u"Показывать на сайте"), default=0)
    show_on_start_page = models.BooleanField(_(u"Показывать на главной странице"), default=0)
    name = models.CharField(_(u"Название"), max_length=255)
    type = models.CharField(_(u"Тип сделки"), choices=TYPE_CHOICES, blank=False, max_length=5, default=0)
    for_students = models.BooleanField(_(u"Также для студентов"), default=0)
    only_for_students = models.BooleanField(_(u"Только для студентов"), default=0)
    # Determinate show object only in students search
    # See description in save method
    students = models.IntegerField(max_length=1, blank=True, default=0, null=True)
    country = models.ForeignKey(Country, blank=False)
    region = models.ForeignKey(Region, blank=False)
    city = models.ForeignKey(City, blank=False)
    price = models.FloatField(_(u"Цена"), default="")
    client_number = models.CharField(_(u"Номер объекта клиента"), max_length=100, blank=True, null=True)
    #price_for_m2 = models.BooleanField(_(u"м2"), default=0) # Is price for m2?
    commission = models.FloatField(_(u"Комиссионные"), default="", blank=True, null=True)
    additional_costs = models.FloatField(_(u"Дополнительные расходы"), default="", blank=True, null=True)
    prepayment = models.FloatField(_(u"Предоплата/Залог"), default="", blank=True, null=True)
    possible_bargain = models.BooleanField(_(u"Возможен торг"), default=0)
    estate_type = models.CharField(_(u"Тип недвижимости"), max_length=15, choices=ESTATE_TYPE_CHOICES, blank=False)
    # One from next aviable_* options are required
    aviable_from = models.DateField(_(u"Доступна с"), blank=True, null=True)
    aviable_to = models.DateField(_(u"Доступна по"), blank=True, null=True)
    aviable_now = models.BooleanField(_(u"Доступна немедленно"), default=0, blank=True)
    rent_for = models.ManyToManyField(RentForChoices, blank=True, verbose_name=RentForChoices._meta.verbose_name)
    built_year = models.IntegerField(_(u"Год постройки"), max_length=4, blank=True, default="", null=True)
    location = models.ManyToManyField(LocationChoices, blank=True, verbose_name=LocationChoices._meta.verbose_name)
    living_space = models.IntegerField(_(u"Жилая площадь"), max_length=4, blank=False)
    #living_space_for_m2 = models.BooleanField(default=0,blank=True)
    total_space = models.IntegerField(_(u"Общая площадь"), max_length=4, blank=True, default="", null=True)
    #total_space_for_m2 = models.BooleanField(default=0)
    land_space = models.IntegerField(_(u"Площадь земельного участка"), max_length=4, blank=True, default="", null=True)
    #land_space_for_m2 = models.BooleanField(default=0)
    rooms_count = models.IntegerField(_(u"Количество комнат"), blank=False, default="")
    bedrooms_count = models.IntegerField(_(u"Количество спальных комнат"), blank=True, default="", null=True)
    floor = models.IntegerField(_(u"Этаж"), blank=True, default="", null=True)
    floor_type = models.ManyToManyField(FloorTypeChoices, blank=True, verbose_name=FloorTypeChoices._meta.verbose_name)
    floors_count = models.IntegerField(_(u"Этажей всего"), max_length=5, blank=True, default="", null=True)
    heating = models.ManyToManyField(HeatingOptions, blank=True)
    floor_covering = models.ManyToManyField(FloorCoveringOptions, blank=True, verbose_name=FloorCoveringOptions._meta.verbose_name)
    kitchens_count = models.IntegerField(_(u"Количество кухонь"), default="", blank=True, null=True)
    kitchen_type = models.ManyToManyField(KitchenChoices, blank=True, verbose_name=KitchenChoices._meta.verbose_name)
    bathrooms_count = models.IntegerField(_(u"Количество ванных комнат"),default="",blank=True, null=True)
    bathroom = models.ManyToManyField(BathroomChoices, blank=True, verbose_name=BathroomChoices._meta.verbose_name)

templates/estates/bookmarks.html
{% extends "base.html" %}
{% load i18n loop_extras cache %}

{% block left_sidebar %} {% include "left_sidebar_search.html" %} {% endblock %}
{% block right_sidebar %} {% include "right_sidebar.html" %} {% endblock %}

{% block content %}

    {% if bookmarks.object_list %}
        <div class="box_title">{% trans "Мои закладки" %}</div>
        <div class="content_box rc5 margin_top_box">
            {% for obj in bookmarks.object_list %}
            <div class="item_list">

                <div class="il_top">
                    <a href="/estates/view/{{ obj.apartment.id }}/">{{ obj.apartment.name|truncate:"28" }}</a>
                    <span>{{ obj.apartment.price|toCurrency:request }}</span>
                </div>

                <div class="il_main">
                    <div class="il_image">
                        {% if obj.apartment.main_image %}
                        <a href="#">
                            <img src="{{ obj.apartment.main_image.photo|thumbnail:"167x111" }}"/>
                        </a>
                        {% else %}
                            <div style="width:90px;font-weight:bold;font-size:26px;padding-top:40px;padding-left:80px">
                                ?
                            </div>
                        {% endif %}
                    </div>
                    <div class="il_content">
                        <p style="height:55px;">
                            {% if obj.apartment.description %}
                                {{ obj.apartment.description|truncate:"135" }}
                            {% else %}
                                {% trans "Нет описания" %}.
                            {% endif %}
                        </p>
                        <p>
                            <span>{% trans "Площадь" %}:</span> {{ obj.apartment.living_space }}
                            {% if obj.apartment.living_space_for_m2 %}
                                m<sup>2</sup>
                            {% endif %}
                        </p>
                        <p>
                            <span>ID:</span> {{ obj.apartment.id }}
                            <a href="#">{{ obj.apartment.country }},</a>
                            <a href="#">{{ obj.apartment.region }},</a>
                            <a href="#">{{ obj.apartment.city }}</a>
                        </p>
                    </div>
                </div>

            </div><!-- item_list END -->
            {% endfor %}

            {% if bookmarks.paginator.count > per_page %}
            <div class="pagination">
                {% if bookmarks.has_previous %}
                    <a href="?page={{ bookmarks.previous_page_number }}"> < </a>
                {% endif %}

                {% for p in bookmarks.paginator.page_range %}
                    {% if p == bookmarks.number %}
                        <span>{{ p }}</span>
                    {% else %}
                        <a href="?page={{ p }}">{{ p }}</a>&nbsp;
                    {% endif %}
                {% endfor %}

                {% if bookmarks.has_next %}
                    <a href="?page={{ bookmarks.next_page_number }}"> > </a>
                {% endif %}
            </div><!-- pagination END -->
            {% endif %}

        </div>
    {% else %}
        {% trans "Список недвижимости пустой" %}.
    {% endif %}
{% endblock %}

templates/estates/form.html
{% extends "base.html" %}
{% load i18n loop_extras cache %}

{% block left_sidebar %} {% include "left_sidebar_search.html" %} {% endblock %}
{% block right_sidebar %} {% include "right_sidebar.html" %} {% endblock %}

{% block head %}
<script type="text/javascript">
$(function(){
    $( "#id_aviable_from" ).datepicker({ dateFormat: 'dd.mm.yy' });
    $( "#id_aviable_to" ).datepicker({ dateFormat: 'dd.mm.yy' });

    $("#apartment_form").relatedSelects({
        onChangeLoad: '/world/load_json/',
        defaultOptionText: '-------',
        selects: {
            'country':		{ loadingMessage:'Loading Regions...' },
            'region':		{ loadingMessage:'Loading Cities...' },
            'city':		{}
        }
    });
});
</script>
{% endblock %}

{% block content %}

    <script type="text/javascript">
        $(function() {
            var html_ul = '';
            $("#tabs_div .tab").each(function(index,el){
                html_ul = html_ul + '<li><a class="rc5" href="#'+$(el).attr('id')+'">'+$(el).attr('title')+'</a></li>';
            });

            html_ul = '<ul class="tabs" id="tabsNavigation">'+html_ul+'</ul>';

            $("#tabs_div").prepend(html_ul).tabs();
            // Delete jquery ui classes.
            $("#tabs_div").removeClass('ui-widget ui-widget-content ui-corner-all');
            $('#tabsNavigation').removeClass().addClass('tabs');
            $('#tabsNavigation li').removeClass().first().addClass('ui-state-selected ui-state-active');
        });

        function clonePhotoFile()
        {
            $("#photo_files").append('<input type="file" name="photo"><br/>');
        }
        function cloneDocumentFile()
        {
            $("#document_files").append('<input type="file" name="document"><br/>');
        }
    </script>

    <form action="" method="post" id="apartment_form" enctype="multipart/form-data">{% csrf_token %}
        <div class="add_item"> 
            <!------- TAB BOX BEGIN ------>
            <div class="tab_box" id="tabs_div">

            <div class="tabs_info rc5">
        
                <div class="form_box">

                    {% if form.errors %}
                    <div id="form-error">
                    <p>{% trans "При заполении формы возникли следующие ошибки"|capfirst %}:</p>
                    <ul>
                        {% for field in form %}
                            {% if field.errors %}
                            <li>{{ field.label }} - {{ field.errors|striptags }}</li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                    </div>
                    {% endif %}

                    {% for field in form %}

                    {% if field.name == 'name_ru' %} <div id="tab1" title="{% trans "Объект"|capfirst %}" class="tab"> {% endif %}
                    {% if field.name == 'price' %} <div id="tab2" title="{% trans "Описание"|capfirst %}" class="tab"> {% endif %}
                    {% if field.name == 'description_ru' %} <div id="tab3" title="{% trans "Доп. данные"|capfirst %}" class="tab"> {% endif %}
                
                    <div class="form_row">
                        <div class="form_text {% if field.field.required%}form_text_required{% endif %}">
                            <label>{{ field.label_tag }}</label>
                        </div>
                        <div class="form_input {% if field.errors %}form_errors{% endif %}">
                            {{ field }}

                            {%  if field.name|slice:"4" == 'dist' %}
                                км
                            {% endif %}

                            {% if field.name == "price" %}
                                {# m² #}
                            {% endif %}
                            {% if field.name == "living_space" %}
                                m²
                            {% endif %}
                            {% if field.name == "total_space" %}
                                m²
                            {% endif %}
                            {% if field.name == "land_space" %}
                               m²
                            {% endif %}
                            {% if field.field.required%}<span style="color:red;"> *</span> {% endif %}
                        </div>
                        <div class="form_overflow"></div>
                    </div>

                    {% if field.name == 'city' %} 
                        <div class="button"><a href="#" onclick='$("#tabs_div").tabs("select",1);scroll(0,0); return true;' class="rc5">{% trans "Далее"|capfirst %}</a></div>
                        </div> 
                    {% endif %}
                    {% if field.name == 'condition' %} 
                        <div class="button"><a href="#" onclick='$("#tabs_div").tabs("select",2);scroll(0,0); return true;' class="rc5">{% trans "Далее"|capfirst %}</a></div>
                        </div> 
                    {% endif %}
                    {% if field.name == 'object_location_de' %} 
                        <div class="button"><a href="#" onclick='$("#tabs_div").tabs("select",3);scroll(0,0); return true;' class="rc5">{% trans "Далее"|capfirst %}</a></div>
                        </div>                         
                    {% endif %}

                {% endfor %}
            
                <div class="tab" id="tab4" title="{% trans "Файлы"|capfirst %}">
                    <h4>{% trans "Изображения"|capfirst %}</h4>

                    {% if form.instance.id %}
                        {% for photo in form.instance.photo_set.all %}
                           <div style="float:left;width:105;height:110px;margin-bottom:10px;">
                           <a href="{{ photo.get_image_url }}">
                               <img src="{{ photo.photo|thumbnail:"100x100" }}" />
                           </a>
                           <br/><label><input type="checkbox" name="delete_image" value="{{ photo.id }}" /> {% trans "Удалить"|capfirst %}</label>
                           </div>
                        {% endfor %}
                        <div style="clear:both;"></div>
                        <br/>
                    {% endif %}

                    <div id="photo_files">
                        <input type="file" name="photo"><br/>
                        <input type="file" name="photo"><br/>
                        <input type="file" name="photo"><br/>
                    </div>    
                    + <a href="#" onclick="clonePhotoFile();">{% trans "Добавить еще одно изображение"|capfirst %}</a>
                    <div style="padding-top:3px;">
                        {% trans "Разрешенный формат"|capfirst %}: gif, jpg, png.<br/>
                        {% trans "Размер фото не должен превышать"|capfirst %} 2мб.
                    </div>
                    <br/><br/>
                    <h4>{% trans "Документы"|capfirst %}</h4>

                    {% if form.instance.id %}
                        {% for doc in form.instance.document_set.all %}
                           <div style="float:left;margin-bottom:10px;">
                           <a href="{{ doc.get_url }}">
                                <img src="{{ doc.icon_url }}" />
                           </a>
                           <br/><label><input type="checkbox" name="delete_doc" value="{{ doc.id }}" /> {% trans "Удалить"|capfirst %}</label>
                           </div>
                        {% endfor %}
                        <div style="clear:both;"></div>
                        <br/>
                    {% endif %}

                    <div id="document_files">
                        <input type="file" name="document"><br/>
                        <input type="file" name="document"><br/>
                        <input type="file" name="document"><br/>
                    </div>
                    + <a href="#" onclick="cloneDocumentFile();">{% trans "Добавить еще один документ"|capfirst %}</a>
                    <div style="padding-top:3px;">
                        {% trans "Разрешенный формат"|capfirst %}: pdf, doc, docx, xls.<br/>
                        {% trans "Размер файла не должен превышать"|capfirst %} 2мб.
                    </div>

                    <div class="button"><a href="#" onclick='$("#tabs_div").tabs("select",4);scroll(0,0); return true;' class="rc5">{% trans "Далее"|capfirst %}</a></div>
                </div>
                <div class="tab" id="tab5" title="{% trans "Сохранить"|capfirst %}">
                    <input type="submit" value="{% trans "Сохранить"|capfirst %}" />
                </div>

                </div><!-- form_box END -->
                 
            </div><!-- tabs_info END -->
        </div>
        <!------- TAB BOX END ------>
    </div><!-- add_item END -->
</form>
{% endblock %}

templates/estates/openimmo.html
{% extends "base.html" %}
{% load i18n loop_extras cache %}

{% block left_sidebar %} {% include "left_sidebar_search.html" %} {% endblock %}
{% block right_sidebar %} {% include "right_sidebar.html" %} {% endblock %}

{% block content %}
<div class="box_title">{% trans "Open Immo" %}</div>
<br/>
<p>
Для загрузки доступны только архивы .zip, в которых должны быть изображения в формате jpeg, а также файлы с описанием недвижимости в формате xml. Ос
тальные файлы будут игнорироваться.<br/><br/>
</p>
	{% if uploaded %}
		<div style="">
			{% trans "Файл успешно загружен" %}
			<br/><br/>
		</div>
	{% endif %}

	{% if errors %}
	<div style="color:red;margin-bottom:10px;">
		{% for e in errors %}
			{{ e }}<br/>
		{% endfor %}
	</div>
	{% endif %}

	<form action="" enctype="multipart/form-data" method="POST">
	{% csrf_token %}
		<input type="file" name="file" />
		<input type="submit" value="{% trans "Загрузить" %}">
	</form>
{% endblock %}

templates/estates/xml_load_form.html
{% extends 'base.html' %}

{% block left_sidebar %} {% include "left_sidebar_search.html" %} {% endblock %}
{% block right_sidebar %} {% include "right_sidebar.html" %} {% endblock %}

{% block content %}
    <p>You can create several appartments at once using xml. Please choose your xml and click 'Load' button</p>
    <br>
    <form method="post" action="" enctype="multipart/form-data" id="appartments_xml_load">
        {% csrf_token %}
        <input type="file" name="xml_file">
        <input type="submit" value="Load">
    </form>
    <hr>
    {% if errors|length %}
        <div style="color:red;margin-bottom:10px;">
            {% for e in errors %}
                {{ e }}<br/>
            {% endfor %}
        </div>
    {% endif %}

    {% if uploaded %}
        Total appartments found: {{ total }}<br>
        Load appartments: {{ loaded }}<br>
        Invalid appartments: {{ invalid }}<br>
    {% endif %}
{% endblock %}